services:
  postgres:
    image: arm64v8/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: kitchensink
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: arm64v8/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpw