services:
  postgres:
    image: arm64v8/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: kitchensink
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  mongo:
    image: arm64v8/mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    volumes:
      - type: bind
        source: ./mongo/data
        target: /Users/jon/workspace/personal/kitchensink/server/docker/mongo/db